language: python

python:
 - 2.6
 - 2.7

install:
 - pip install -e git+https://github.com/qingfeng/misaka.git@2fbe52692e8f304eea9d8925fd2a857916ff0ea5#egg=Misaka
 - python setup.py install

script:
 - python setup.py test
